apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: andrey
spec:
  rules:
    - host: andrey.workshop.cappasity3d.com
      http:
        paths:
          - path: /
            backend:
              serviceName: ms-andrey
              servicePort: 3000
